name: CI

# מגדיר מתי להפעיל את ה-workflow
on:
  push:
    branches:
      - feature/my-second-change   # כל push ל-branch הזה
  pull_request:
    branches:
      - main                       # כל PR ל-main

jobs:
  test:
    runs-on: ubuntu-latest        # מערכת ההפעלה של runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # מוריד את הקוד שלך ל-runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'    # מתקין Python 3

      - name: Run app
        run: python app.py          # מריץ את הקובץ app.py
